---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Install python
      raw: sudo apt-get install -y python

- hosts: all
  become: yes
  tasks:
    - name: Install curl
      package: name=curl state=latest
  roles:
    - elasticsearch-ansible
